export const plans = [
    {
        company: "楽天モバイル",
        plan: "Rakuten UN-LIMIT VII",
        price: "¥3,278/月",
        data: "無制限 (条件付き)",
        voice: "Rakuten Linkアプリで無料通話",
        link: 'https://network.mobile.rakuten.co.jp/',
        score: 10,
    },
    {
        company: "au",
        plan: "使い放題MAX 5G/4G",
        price: "¥7,238/月",
        data: "無制限",
        voice: "家族割で1,100円割引",
        link: 'https://www.au.com/',
        score: 8,
    },
    {
        company: "SoftBank",
        plan: "メリハリ無制限",
        price: "¥7,238/月",
        data: "無制限",
        voice: "家族割で1,100円割引",
        link: 'https://www.softbank.jp/mobile/',
        score: 8,
    },
    {
        company: "docomo",
        plan: "ahamo",
        price: "¥2,970/月",
        data: "20GB",
        voice: "5分以内の国内通話無料",
        link: 'https://www.docomo.ne.jp/',
        score: 6,
    },
];

export const cheapSimPlans = [
    {
        company: "楽天モバイル",
        plan: "Rakuten UN-LIMIT VII",
        price: "¥3,278/月",
        data: "無制限（条件付き）",
        voice: "Rakuten Linkアプリで無料通話",
        link: "https://network.mobile.rakuten.co.jp/",
        score: 10,
    },
    {
        company: "UQモバイル",
        plan: "くりこしプラン +5G",
        price: "¥1,628～¥3,828/月",
        data: "3GB～25GB",
        voice: "国内通話 22円/30秒",
        link: "https://www.uqwimax.jp/",
        score: 7,
    },
    {
        company: "Y!mobile",
        plan: "シンプルプラン",
        price: "¥2,178～¥4,158/月",
        data: "3GB～25GB",
        voice: "国内通話 22円/30秒",
        link: "https://www.ymobile.jp/",
        score: 7,
    },
    {
        company: "IIJmio",
        plan: "ギガプラン",
        price: "¥850～¥1,980/月",
        data: "2GB～20GB",
        voice: "通話オプションあり",
        link: "https://www.iijmio.jp/",
        score: 5,
    },
    {
        company: "mineo",
        plan: "マイピタ",
        price: "¥1,298～¥2,178/月",
        data: "1GB～20GB",
        voice: "通話オプションあり",
        link: "https://mineo.jp/",
        score: 5,
    },
    {
        company: "OCN モバイル ONE",
        plan: "OCN モバイル ONE プラン",
        price: "¥550～¥1,760/月",
        data: "500MB～10GB",
        voice: "国内通話 11円/30秒",
        link: "https://service.ocn.ne.jp/mobile/",
        score: 4,
    },
    {
        company: "BIGLOBEモバイル",
        plan: "音声通話SIM",
        price: "¥1,078～¥1,870/月",
        data: "1GB～20GB",
        voice: "国内通話 9円/30秒",
        link: "https://join.biglobe.ne.jp/mobile/",
        score: 5,
    },
    {
        company: "LINEMO",
        plan: "ミニプラン・スマホプラン",
        price: "¥990～¥2,728/月",
        data: "3GB～20GB",
        voice: "LINE通話無料",
        link: "https://www.linemo.jp/",
        score: 6,
    },
];

export const otherSimCompanies = [
    { company: "イオンモバイル", link: "https://aeonmobile.jp/" },
    { company: "nuroモバイル", link: "https://mobile.nuro.jp/" },
    { company: "J:COM MOBILE", link: "https://www.jcom.co.jp/service/mobile/" },
    { company: "ロケットモバイル", link: "https://rocketmobile.jp/" },
    { company: "LinksMate", link: "https://linksmate.jp/" },
    { company: "日本通信SIM", link: "https://www.nihontsushin.com/sim/" },
    { company: "HISモバイル", link: "https://his-mobile.com/" },
    { company: "b-mobile", link: "https://www.bmobile.ne.jp/" },
];